98% fully working IPC, done using using a relay server
CaelumD25/networked_pacman pull request #1
Opened 2024-03-30 06:45 UTC by CaelumD25

If you guys could checkout this branch and see if you're able to run it without any issues that would be great!

To install the requirements for the python packages, just write `pip install requirements.txt` when in the root folder.

2024-03-30 16:25 UTC, bmachado18 commented
Running all the test cases in one process gives weird behavior, and ends up failing last two test cases. To solve, test each case in isolation. Otherwise the new IPC is working great for me.

2024-03-30 19:31 UTC, CaelumD25 commented
> 3\. run the unit tests and observe

Opening the tests in an IDE should allow you to run them by pressing the play arrows in the margin on the left

2024-04-03 05:26 UTC, Decruz24 commented on relay.py
> +
Had to import JSON here so connect worked properly for me

2024-04-03 05:29 UTC, Decruz24 commented on python/graph.py
Ill get started on this next. Going to make a new branch for this

2024-04-03 05:34 UTC, Decruz24 requested changes
Looks really good to me! Just needed to import JSON in relay.py

Thanks for doing so much! I have no idea how you figured this out but it works pretty well.

2024-04-04 02:45 UTC, merged